#Before using this file the variables EVENTS_EXTERNAL_PORT 
#and NOTIFICATIONS_EXTERNAL_PORT must be set.
version: "3"

services:
  events_container:
    build:
      context: .
      dockerfile: Dockerfile.events
    ports:
      - "$EVENTS_EXTERNAL_PORT:8080"
  notifications_container:
    build:
      context: .
      dockerfile: Dockerfile.notifications
    ports:
      - "$NOTIFICATIONS_EXTERNAL_PORT:8080"
